---
# Installs cacti via dockercontainer on a linux host

- name: create /etc/docker/compose/cacti directory
  file:
    path: /etc/docker/compose/cacti
    state: directory

- name: create /opt/cacti directory
  file:
    path: /opt/cacti
    state: directory
    
- name: copy docker-compose template
  template: 
    src: docker-compose.yml.j2
    dest: /etc/docker/compose/cacti/docker-compose.yml
  register: cacti_config

- name: copy systemd service file
  copy: 
    src: cacti.service
    dest: /etc/systemd/system/cacti.service
  register: cacti_systemd

- name: force systemd to reread configs
  systemd: daemon_reload=yes
  when: cacti_systemd.changed

- name: restart cacti service
  service: name=cacti state=restarted enabled=yes
  when: cacti_systemd.changed or cacti_config.changed
