---
# This playbook updates a system

- name: apply common configuration to all nodes
  hosts: docker
  become: true
  roles:
    - system-common
    - docker
    - netdata
    - portainer-agent
    - newrelic
