---
# This playbook updates a system

- name: LibreNMS Master
  hosts: librenms
  become: true
  roles:
    - common
    - docker
    - netdata
    - librenms

- name: LibreNMS Pollers
  hosts: librenms_poller
  become: true
  roles:
    - common
    - docker
    - netdata
    - librenms_poller
