#- name: create required directories
#  file:
#    path: "{{ item }}"
#    state: directory
#    with_items:
#      - /etc/docker/compose
#      - /etc/docker/compose/minecraft-map
#      - /var/minecraft-map
#      - /var/minecraft-map/vanilla
#      - /var/minecraft-map/pixelmon
#      - /var/minecraft-map/vanilla-raw
#      - /var/minecraft-map/pixelmon-raw
#      - /var/minecraft-map/vanilla-www
#      - /var/minecraft-map/pixelmon-www
#      - /mnt/nfs/darkwindcraft

- name: create required directories
  file:
    path: /etc/docker/compose
    state: directory
- file:
    path: /etc/docker/compose/minecraft-map
    state: directory
- file:
    path: /var/minecraft-map
    state: directory
- file:
    path: /var/minecraft-map/vanilla-raw
    state: directory
- file:
    path: /var/minecraft-map/arckeya-raw
    state: directory
- file:
    path: /var/minecraft-map/pixelmon-raw
    state: directory
- file:
    path: /mnt/nfs/darkwindcraft
    state: directory
- file:
    path: /mnt/nfs/arckeya
    state: directory

- name: install nfs client software
  yum:
    name: nfs-utils
    state: present

- name: Mount up device by label
  mount:
    path: /mnt/nfs/darkwindcraft
    src: "{{ NFS_SHARE }}"
    fstype: nfs
    state: mounted

- name: Mount up device by label
  mount:
    path: /mnt/nfs/arckeya
    src: "{{ NFS_SHARE_02 }}"
    fstype: nfs
    state: mounted

- name: install unzip
  yum:
    name: unzip
    state: present

- name: copy sync script
  copy: 
    src: sync.sh
    dest: /etc/docker/compose/minecraft-map/sync.sh

- name: copy minecraft overworld configuration
  copy: 
    src: config.py
    dest: /etc/docker/compose/minecraft-map/config.py

- name: copy docker-compose template
  template: 
    src: docker-compose.yml.j2
    dest: /etc/docker/compose/minecraft-map/docker-compose.yml
  notify: restart minecraft-map service

- name: copy systemd service file
  copy: 
    src: minecraft-map.service
    dest: /usr/lib/systemd/system/minecraft-map.service
  register: minecraftmap_systemd
  notify: restart minecraft-map service

- name: force systemd to reread configs
  systemd: daemon_reload=yes
  when: minecraftmap_systemd.changed

- name: open port 8080 on firewalld
  firewalld:
    port: "8080/tcp"
    permanent: yes
    state: enabled

- name: open port 8081 on firewalld
  firewalld:
    port: "8081/tcp"
    permanent: yes
    state: enabled

- name: open port 8082 on firewalld
  firewalld:
    port: "8082/tcp"
    permanent: yes
    state: enabled

- name: Changing perm of "/etc/docker/compose/minecraft-map/sync.sh", adding "+x"
  file: dest=/etc/docker/compose/minecraft-map/sync.sh mode=a+x

- name: Render from backup at 13:00 and 01:00
  cron:
    name: "Render Maps"
    minute: "0"
    hour: "13,1"
    job: "/bin/bash /etc/docker/compose/minecraft-map/sync.sh"
