---
# Installs Netdata via dockercontainer on a linux host

- name: create /etc/docker/compose/netdata directory
  file:
    path: /etc/docker/compose/netdata
    state: directory

- name: copy docker-compose template
  template: 
    src: docker-compose.yml.j2
    dest: /etc/docker/compose/netdata/docker-compose.yml
  register: netdata_compose
  notify: restart netdata service

- name: copy systemd service file
  copy: 
    src: netdata.service
    dest: /etc/systemd/system/netdata.service
  register: netdata_systemd
  notify: restart netdata service
