---
# Installs Netdata via dockercontainer on a linux host

- name: create /etc/docker/compose/netdata directory
  file:
    path: /etc/docker/compose/netdata
    state: directory

- name: copy docker-compose template
  template: 
    src: docker-compose.yml.j2
    dest: /etc/docker/compose/netdata/docker-compose.yml
  notify: restart netdata service

- name: copy systemd service file
  copy: 
    src: netdata.service
    dest: /usr/lib/systemd/system/netdata.service
  register: netdata_systemd
  notify: restart netdata service

- name: force systemd to reread configs
  systemd: daemon_reload=yes
  when: netdata_systemd.changed
  tags: netdata

- name: open port 19999 on firewalld
  firewalld:
    port: 19999/tcp
    permanent: yes
    state: enabled
  tags: netdata
  