---
# Installs Netdata via dockercontainer on a linux host
- name: install nfs client software
  yum:
    name: nfs-utils
    state: present

- name: create /mnt/nfs/docker directory
  file:
    path: /mnt/nfs/docker
    state: directory

- name: create /mnt/nfs/docker directory
  file:
    path: /mnt/nfs/docker/{{ NFS_DOCKER_DIRECTORY }}
    state: directory

- name: Mount up device by label
  mount:
    path: /mnt/nfs/docker
    src: "{{ NFS_SHARE }}"
    fstype: nfs
    state: mounted

- name: create /etc/docker/compose/wordpress directory
  file:
    path: /etc/docker/compose/wordpress
    state: directory

- name: copy docker-compose template
  template: 
    src: docker-compose.yml.j2
    dest: /etc/docker/compose/wordpress/docker-compose.yml
  notify: restart wordpress service

- name: copy systemd service file
  copy: 
    src: wordpress.service
    dest: /usr/lib/systemd/system/wordpress.service
  register: wordpress_systemd
  notify: restart wordpress service

- name: copy upload settings file
  copy: 
    src: uploads.ini
    dest: /mnt/nfs/docker/{{ NFS_DOCKER_DIRECTORY }}/uploads.ini
  register: wordpress_systemd
  notify: restart wordpress service

- name: copy wordpress configuration
  template: 
    src: wp-config.php.j2
    dest: /mnt/nfs/docker/{{ NFS_DOCKER_DIRECTORY }}/wp-config.php
  notify: restart wordpress service

- name: force systemd to reread configs
  systemd: daemon_reload=yes
  when: wordpress_systemd.changed
  tags: wordpress

- name: open port 8000 on firewalld
  firewalld:
    port: 8000/tcp
    permanent: yes
    state: enabled
  tags: wordpress
