---
# Installs Netdata via dockercontainer on a linux host

- name: create /etc/docker/compose/wordpress directory
  file:
    path: /etc/docker/compose/wordpress
    state: directory

- name: copy docker-compose template
  template: 
    src: docker-compose.yml.j2
    dest: /etc/docker/compose/wordpress/docker-compose.yml
  notify: restart wordpress service

- name: copy systemd service file
  copy: 
    src: wordpress.service
    dest: /usr/lib/systemd/system/wordpress.service
  register: wordpress_systemd
  notify: restart wordpress service

- name: copy upload settings file
  copy: 
    src: uploads.ini
    dest: /etc/docker/compose/wordpress/uploads.ini
  register: wordpress_systemd
  notify: restart wordpress service

- name: force systemd to reread configs
  systemd: daemon_reload=yes
  when: wordpress_systemd.changed
  tags: wordpress

- name: open port 8000 on firewalld
  firewalld:
    port: 8000/tcp
    permanent: yes
    state: enabled
  tags: wordpress
