---
# Installs Netdata via dockercontainer on a linux host
- name: install nfs client software
  yum:
    name: nfs-utils
    state: present

- name: create /mnt/nfs/darkwindcraft directory
  file:
    path: /mnt/nfs/darkwindcraft
    state: directory

- name: create /mnt/nfs/arckeya directory
  file:
    path: /mnt/nfs/arckeya
    state: directory

- name: Mount up device by label
  mount:
    path: /mnt/nfs/darkwindcraft
    src: "{{ NFS_SHARE }}"
    fstype: nfs
    state: mounted

- name: Mount up device by label
  mount:
    path: /mnt/nfs/arckeya
    src: "{{ NFS_SHARE_02 }}"
    fstype: nfs
    state: mounted

- name: create /etc/docker/compose/nextcloud directory
  file:
    path: /etc/docker/compose/nextcloud
    state: directory

- name: copy docker-compose template
  template: 
    src: docker-compose.yml.j2
    dest: /etc/docker/compose/nextcloud/docker-compose.yml
  notify: restart nextcloud service

- name: copy systemd service file
  copy: 
    src: nextcloud.service
    dest: /usr/lib/systemd/system/nextcloud.service
  register: nextcloud_systemd
  notify: restart nextcloud service

- name: copy nginx configuration
  copy: 
    src: nginx.conf
    dest: /etc/docker/compose/nextcloud/nginx.conf
  notify: restart nextcloud service

- name: force systemd to reread configs
  systemd: daemon_reload=yes
  when: nextcloud_systemd.changed

- name: open port on firewalld
  firewalld:
    port: "{{ NEXTCLOUD_LISTENING_PORT }}/tcp"
    permanent: yes
    state: enabled
