---
# This playbook updates a system

- name: apply common configuration to all nodes
  hosts: dockercompute
  become: true
  roles:
    - common
    - docker
    - netdata
    - telegraf
    - prometheus
    - portainer-agent
