---
# Installs exabgp-pihole via dockercontainer on a linux host

- name: configure the exabgp service settings
  template: 
    src=exabgp-pihole.service.j2
    dest=/usr/lib/systemd/system/exabgp-pihole.service
  register: exabgp_pihole_systemd
  notify: restart exabgp-pihole service

- name: create exabgp directory
  file: path=/var/docker/exabgp/ state=directory       

- name: force systemd to reread configs
  systemd: daemon_reload=yes
  when: exabgp_pihole_systemd.changed

- name: configure the exabgp-pihole configuration file
  template: 
    src=exabgp.conf.j2
    dest=/var/docker/exabgp/exabgp.conf
  register: exabgp_config
  notify: restart exabgp-pihole service

- name: allow bgp and pihole through firewall
  shell: firewall-cmd --add-port=179/tcp --add-port=53/tcp --add-port=53/udp --add-port=67/udp --add-port=80/tcp --add-port=443/tcp --permanent
  notify: firewall reload
