---
# Installs prom via dockercontainer on a linux host

- name: create /etc/docker/compose/prom directory
  file:
    path: /etc/docker/compose/prom
    state: directory

- name: copy docker-compose template
  template: 
    src: docker-compose.yml.j2
    dest: /etc/docker/compose/prom/docker-compose.yml
  notify: restart prom service

- name: copy systemd service file
  copy: 
    src: prom.service
    dest: /usr/lib/systemd/system/prom.service
  register: prom_systemd
  notify: restart prom service

- name: force systemd to reread configs
  systemd: daemon_reload=yes
  when: prom_systemd.changed
  tags: prom
