---
# configure ntp settings
- include_tasks: centos-ntp.yml
  when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version != '8') or ansible_distribution == 'Red Hat Enterprise Linux'

# disable selinux
- include_tasks: centos-selinux.yml
  when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version != '8') or ansible_distribution == 'Red Hat Enterprise Linux'
