---
- name: update remote authorized SSH keys for future ansible runs
  authorized_key: 
    user: "{{ lookup('env','USER') }}" 
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  ignore_errors: yes

- include_tasks: centos-common.yml
  when: ansible_os_family == "RedHat"

- include_tasks: ubuntu-common.yml
  when: ansible_distribution == 'Ubuntu'

- include_tasks: vmtools.yml
  when: ansible_virtualization_type == "VMware"

- include_tasks: update.yml
  when: ansible_os_family == "RedHat" or ansible_distribution == 'Ubuntu'
