---
- name: Install NTP
  apt: package=ntp,ntpdate state=present update_cache=yes

- name: Make sure NTP is started up
  service: name=ntp state=started enabled=yes

- name: Set timezone
  timezone:
    name: "{{ server_timezone }}"
