---

- name: Ubuntu | Install dependencies
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg-agent
    update_cache: yes
    cache_valid_time: 3600

- name: Ubuntu | Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Ubuntu | Add stable docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present

- name: Ubuntu | Install Docker
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - docker-compose
    update_cache: yes
    cache_valid_time: 3600

- name: Ubuntu | Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: 
      - docker
    append: yes
