---
- name: Ubuntu | Install NTP
  apt: 
    name: ntp
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Ubuntu | Start NTP service
  service: 
    name: ntp 
    state: started 
    enabled: yes

- name: Ubuntu | Set system timezone
  timezone:
    name: "{{ server_timezone }}"
