---
- name: ubuntu | installing open-vm-tools
  apt: 
    name: open-vm-tools
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: ubuntu | setting swappiness to 1
  sysctl:
    name: vm.swappiness
    value: "1"
    state: present
