---
# https://linuxconfig.org/how-to-install-docker-in-rhel-8#h5-installing-docker-compose
- name: Grab docker-compose from github
  get_url:
    url: https://github.com/docker/compose/releases/download/1.23.2/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose
  become: yes

- name: Changing perm of "/usr/local/bin/docker-compose", adding "+x"
  file: dest=/usr/bin/docker-compose mode=a+x
  become: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
