---
# Installs plex via dockercontainer on a linux host
- name: install nfs client software
  yum:
    name: nfs-utils
    state: present

- name: create /mnt/nfs/plex directory
  file:
    path: /mnt/nfs/plex
    state: directory

- name: Mount up device by label
  mount:
    path: /mnt/nfs/plex
    src: "{{ NFS_SHARE }}"
    fstype: nfs
    state: mounted

# https://forums.plex.tv/t/error-transcoder-ac3_eae-0x2fd4f40-eae-timeout-eae-not-running-or-wrong-folder/189917
- sysctl:
  name: fs.inotify.max_user_watches
  value: 16384
  state: present

- name: create /etc/docker/compose/plex directory
  file:
    path: /etc/docker/compose/plex
    state: directory

- name: copy docker-compose template
  template: 
    src: docker-compose.yml.j2
    dest: /etc/docker/compose/plex/docker-compose.yml
  notify: restart plex service

- name: copy systemd service file
  copy: 
    src: plex.service
    dest: /usr/lib/systemd/system/plex.service
  register: plex_systemd
  notify: restart plex service

- name: force systemd to reread configs
  systemd: daemon_reload=yes
  when: plex_systemd.changed

- name: open port on firewalld
  firewalld:
    port: 32400/tcp
    permanent: yes
    state: enabled
