---
# Ubuntu only tasks
- name: Ubuntu only tasks
  include_tasks: "{{ item }}"
  loop:
    - ubuntu-update.yml
    - ubuntu-clean.yml
    - ubuntu-reboot.yml
  when: ansible_distribution == 'Ubuntu'
